version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27018:27017'
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodata:
